/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ziv_jni_collection_HelloJni_Name */

#ifndef _Included_com_ziv_jni_collection_HelloJni_Name
#define _Included_com_ziv_jni_collection_HelloJni_Name
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ziv_jni_collection_HelloJni_Name
 * Method:    setNewName
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ziv_jni_collection_HelloJni_00024Name_setNewName
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
