/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ziv_jni_collection_HelloJni */

#ifndef _Included_com_ziv_jni_collection_HelloJni
#define _Included_com_ziv_jni_collection_HelloJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ziv_jni_collection_HelloJni
 * Method:    getAJNIString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ziv_jni_collection_HelloJni_getAJNIString
  (JNIEnv *, jobject);

/*
 * Class:     com_ziv_jni_collection_HelloJni
 * Method:    getTwoArray
 * Signature: (I)[[I
 */
JNIEXPORT jobjectArray JNICALL Java_com_ziv_jni_collection_HelloJni_getTwoArray
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
