/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "android/log.h"
/* Header for class com_ziv_jni_log_LogPrint */

#ifndef _Included_com_ziv_jni_log_LogPrint
#define _Included_com_ziv_jni_log_LogPrint
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ziv_jni_log_LogPrint
 * Method:    print
 * Signature: (Ljava/lang/String;)V
 * 第二个参数jclass/jobject的意义，要看方法是不是静态的（static）或者实例（Instance）的。
 * jclass代表一个类对象的引用，而jobject是被调用的方法所属对象的引用。
 */
JNIEXPORT void JNICALL Java_com_ziv_jni_log_LogPrint_print
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
