/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "jni_log_util.h"
/* Header for class com_ziv_thread_NativeThread */

#ifndef _Included_com_ziv_thread_NativeThread
#define _Included_com_ziv_thread_NativeThread
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ziv_thread_NativeThread
 * Method:    start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ziv_thread_NativeThread_start
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
